---
- hosts: all
  connection: local
  tasks:
  - name: Verify VLAN
    ios_command:
      commands: 
         - show run int {{ interface }}          
    register: int

  - name: Print output
    debug:
       var: "output.stdout_lines"
