---
- hosts: all
  connection: local
  tasks:
  - name: Show_Run_Interface
    ios_command:
      commands: 
         - show run int {{ interface }}          
    register: output

  - name: Print output
    debug:
       var: "output.stdout_lines"
